; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2 on Fri Jan 25 2019 22:15:29 GMT-0700 (Mountain Standard Time)
M280 P60 S160 I0                           ; Reset any bltouch errors
M280 P60 S10 I0

