; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Fri Jan 25 2019 22:15:31 GMT-0700 (Mountain Standard Time)

